---
- name: Run command on MikroTik Router
  hosts: mikrotik
  gather_facts: no
  tasks:
    - name: Print Interface
      tags: nana
      community.routeros.command:
        commands:
          - interface print
      register: i
    - name: Show output
      debug:
        var: i.stdout


- name: Run command on MikroTik Router
  hosts: mik
  gather_facts: no
  tasks:
    - name: Print IP
      tags: brody
      community.routeros.command:
        commands:
          - ip address print
      register: s
    - name: Show output
      debug:
        var: s.stdout
      tags: brody


- name: Run command on MikroTik Router
  hosts: rout
  gather_facts: no
  tasks:
    - name: Print both
      tags: bane
      community.routeros.command:
        commands:
          - interface print
          - ip address print
      register: a
    - name: Show output
      debug:
        var: a.stdout
