  GNU nano 8.6                                                               all.yml
ansible_user: admin
ansible_password: !vault |
$ANSIBLE_VAULT;1.1;AES256
          36613539663033643835663362653835623166343436316561383237393237363430363732643237
          6633306163613064306261613664633738376666306634380a646364643836643764366131333161
          30366166373233363031313735356338666333386264376562666665656664623662306266656162
          3439333266376538610a386132613431383637303662386139343034306434363336323661656364
          3166
router_ip:
  r1: 192.168.1.104
  r2: 192.168.1.108
router_gateway:
  r1: 192.168.1.1
  r2: 192.168.1.1
